# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

sql = Language.create(lang_name: "SQL", history: "SQL was initially developed at IBM by Donald D. Chamberlin and Raymond F. Boyce after learning about the relational model from Ted Codd[15] in the early 1970s.[16] This version, initially called SEQUEL (Structured English Query Language), was designed to manipulate and retrieve data stored in IBM's original quasi-relational database management system, System R, which a group at IBM San Jose Research Laboratory had developed during the 1970s", jobs_available: 765626, average_salary: 95000, description: "SQL (structured query language) is a special-purpose language used for database management. SQL is one of the few declarative programming languages, so there’s a learning curve for programmers used to object-oriented or imperative languages. But the numbers don’t lie—SQL is an in-demand programming language that’s worth the time it takes to learn.", video: 'https://www.youtube.com/watch?v=nWeW3sCmD2k',
blog: "https://www.sohamkamani.com/blog/2016/07/07/a-bigginers-guide-to-sql/",
course: "https://www.udemy.com/the-ultimate-mysql-bootcamp-go-from-sql-beginner-to-expert/",
book: "https://www.amazon.com/SQL-Programming-Management-Step-Step-ebook/dp/B01MDV363Y/ref=sr_1_1_sspa?ie=UTF8&qid=1527711027&sr=8-1-spons&keywords=SQL&psc=1", school: "https://flatironschool.com/")

java = Language.create(lang_name: "Java", history: "James Gosling, Mike Sheridan, and Patrick Naughton initiated the Java language project in June 1991.[27] Java was originally designed for interactive television, but it was too advanced for the digital cable television industry at the time.[28] The language was initially called Oak after an oak tree that stood outside Gosling's office. Later the project went by the name Green and was finally renamed Java, from Java coffee.[29] Gosling designed Java with a C/C++-style syntax that system and application programmers would find familiar.", jobs_available: 387533, average_salary: 111000, description: "Java is a general-purpose language that shares much of its syntax with C and C++. It is class-based, object-oriented programming thats used to develop many of the apps we use on a daily basis. Many websites will not even work properly without Java apps. Java is a good option for someone new to programming thanks to the plethora of tutorials and learning resources available online.",
video: "https://www.youtube.com/watch?v=r59xYe3Vyks&list=PLS1QulWo1RIbfTjQvTdj8Y6yyq4R7g-Al", blog: "https://vladmihalcea.com/tag/blogging/", course: "https://www.codecademy.com/learn/learn-java", book: "https://www.amazon.com/Java-Beginners-Seventh-Herbert-Schildt-ebook/dp/B075K7BPN6/ref=sr_1_4?ie=UTF8&qid=1527716421&sr=8-4&keywords=Java&dpID=51HIt7ThIzL&preST=_SX342_QL70_&dpSrc=srch", school: "https://bootcamp.cvn.columbia.edu/landing/?s=Google-Unbranded&trkid=V3ADW427732_48765669730_kwd-296505127639__258384776781_g_c__&mkwid=90mi5JVC_dc&pkw=%2Bjava%20%2Blearn&pcrid=258384776781&pmt=b&utm_source=google&utm_medium=cpc&utm_campaign=&utm_term=%2Bjava%20%2Blearn&utm_content=258384776781&s=google&k=%2Bjava%20%2Blearn&gclid=Cj0KCQjwl7nYBRCwARIsAL7O7dEbMZemqtLAJOj2VxwAKHtPmE3hOAEuR0iZle0NGL2XR2PttDlWHrQaAhtBEALw_wcB&utm_expid=.ET4Nh4HmRvubOCvi--O5NA.0&utm_referrer=https%3A%2F%2Fwww.google.com%2F")

javascript = Language.create(lang_name: "Javascript", history: "In 1993, the National Center for Supercomputing Applications (NCSA), a unit of the University of Illinois at Urbana-Champaign, released NCSA Mosaic, the first popular graphical Web browser, which played an important part in expanding the growth of the nascent World Wide Web. In 1994, a company called Mosaic Communications was founded in Mountain View, California and employed many of the original NCSA Mosaic authors to create Mosaic Netscape.", jobs_available: 366476, average_salary: 104000, description: "JavaScript is a dynamic programming language used most often with internet browsers. You can also find it in game development, PDFs and both mobile and desktop apps. With its plentiful job opportunities and an easily managed learning curve, some programmers argue JavaScript is the ideal programming language for beginners.", video: "https://www.youtube.com/watch?v=PwsigsH4oXw", blog: "http://jsfeeds.com/",
book: "https://www.amazon.com/Mastering-JavaScript-Functional-Programming-depth/dp/1787287440/ref=sr_1_1_sspa?ie=UTF8&qid=1527716778&sr=8-1-spons&keywords=javascript&psc=1", school: "https://flatironschool.com/programs/online-intro-javascript-free-course/")

python = Language.create(lang_name: "Python", history: "Python was conceived in the late 1980s,[29] and its implementation began in December 1989[30] by Guido van Rossum at Centrum Wiskunde & Informatica (CWI) in the Netherlands as a successor to the ABC language (itself inspired by SETL)[31] capable of exception handling and interfacing with the Amoeba operating system.", jobs_available: 247958, average_salary: 120000, description: "Python is a general-use programming language known for its readability and straightforward coding philosophy. Complexity is not a good thing to a Python programmer. It’s used by both Google and YouTube, is easy to learn for newcomers and was named after Monty Python. What’s not to love?", video: "https://www.youtube.com/watch?v=N4mEzFDjqtA", blog: "http://planetpython.org/", course: "https://www.udacity.com/course/programming-foundations-with-python--ud036", book: "https://www.amazon.com/gp/product/1593276036/ref=s9_acsd_top_hd_bw_b1CMa_c_x_1_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-3&pf_rd_r=Q70BGXPKQPRPEJ5QN5ES&pf_rd_t=101&pf_rd_p=08266f12-f2bb-5d63-89ce-72b596f1a48f&pf_rd_i=285856", school: "https://flatironschool.com/programs/data-science-bootcamp/")

c_sharp = Language.create(lang_name: "C#", history: "During the development of the .NET Framework, the class libraries were originally written using a managed code compiler system called Simple Managed C (SMC).[17][18] In January 1999, Anders Hejlsberg formed a team to build a new language at the time called Cool, which stood for 'C-like Object Oriented Language'. Microsoft had considered keeping the name 'Cool' as the final name of the language, but chose not to do so for trademark reasons. By the time the .NET project was publicly announced at the July 2000 Professional Developers Conference, the language had been renamed C#, and the class libraries and ASP.NET runtime had been ported to C#.", jobs_available: 232179, average_salary: 100000, description: "C# (pronounced 'C sharp') is a language developed by Microsoft for use within .NET, meaning its one of the primary languages for programming in Windows. C# takes its cues from C++ and Java while adding a focus on simplicity and flexibility. C# plays a key role in programming for the internet, which means this language is not likely to fizzle out in the foreseeable future.",
video: "https://www.youtube.com/watch?v=2lAdQ_QwNww", blog: "https://medium.com/@jakubgarfield/how-to-keep-up-to-date-as-a-c-developer-387bff208158", course: "https://mva.microsoft.com/en-us/training-courses/c-fundamentals-for-absolute-beginners-16169?l=Lvld4EQIC_2706218949", book: "https://www.amazon.com/gp/product/B016Z18MLG/ref=s9_acsd_top_hd_bw_b2vPS_c_x_1_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-3&pf_rd_r=ZYVZVZMYW5DJDKX2K3E9&pf_rd_t=101&pf_rd_p=cc8b66c7-db75-5fb5-932f-9f280c1a3534&pf_rd_i=697342", school: "https://www.codeschool.com/courses/try-c-sharp")

cplusplus = Language.create(lang_name: "C++", history: "In 1979, Bjarne Stroustrup, a Danish computer scientist, began work on C with Classes, the predecessor to C++. The motivation for creating a new language originated from Stroustrup's experience in programming for his Ph.D. thesis. Stroustrup found that Simula had features that were very helpful for large software development, but the language was too slow for practical use, while BCPL was fast but too low-level to be suitable for large software development.", jobs_available: 186364, average_salary: 111000, description: "C++ is a compiled language designed for system programming, though it’s also used in desktop apps and e-commerce servers. It was originally created to improve upon C by combining efficiency, flexibility and object-oriented programming. C++ is notorious for being a bit complicated, but anyone familiar with C will have a leg up in learning C++.", video: "https://www.youtube.com/watch?v=Rub-JsjMhWY", blog:
"https://isocpp.org/blog", course: "https://www.edx.org/course/introduction-to-c-plus-plus", book: "https://www.amazon.com/C-Programming-Language-4th/dp/0321563840/ref=zg_bs_9045760011_1?_encoding=UTF8&psc=1&refRID=X4Q1E01PD60WGJ6V2TTQ")

perl = Language.create(lang_name: "PERL", history: "Larry Wall began work on Perl in 1987, while working as a programmer at Unisys,[14] and released version 1.0 to the comp.sources.misc newsgroup on December 18, 1987.[22] The language expanded rapidly over the next few years. Perl 2, released in 1988, featured a better regular expression engine. Perl 3, released in 1989, added support for binary data streams. Perl 5.6 was released on March 22, 2000. Major changes included 64-bit support, Unicode string representation, support for files over 2 GiB, and the 'our' keyword.", jobs_available: 127893, average_salary: 110000 , description: "Perl is a scripting language most often used for CGI scripts, systems administration and network programming. Much of Perl\’s source code is available online, giving aspiring programmers the chance to learn by example. Despite its perks, many programmers think Perl is unappealing and unwieldy. Perl\’s 'ugliness' is a byproduct of its flexibility. In fact, one of the guiding mottos of Perl programming is 'There\’s more than one way to do it.'",
video: "https://www.youtube.com/watch?v=WEghIXs8F6c", blog: "http://blogs.perl.org/")

php = Language.create(lang_name: "PHP", history: "PHP development began in 1994 when Rasmus Lerdorf wrote several Common Gateway Interface (CGI) programs in C,[9][10][11] which he used to maintain his personal homepage. He extended them to work with web forms and to communicate with databases, and called this implementation 'Personal Home Page/Forms Interpreter' or PHP/FI.", jobs_available: 98021, average_salary: 100000, description: "PHP is a general-purpose scripting language designed for web development. It\’s used to beef up basic HTML—forums, surveys and login pages are all created with PHP. It can even be used to develop desktop apps. PHP is an ideal choice if you\’re seeking a future in web development.", video: "https://www.youtube.com/watch?v=7TF00hJI78Y", )

ruby = Language.create(lang_name: "Ruby", history: "Matsumoto has said that Ruby was conceived in 1993. In a 1999 post to the ruby-talk mailing list, he describes some of his early ideas about the language", jobs_available: 80389, average_salary: 120000, description: "Ruby is the ultimate blend of simple and functional programming. This flexible, object-oriented language is used in text processing and middleware programs. It can also be used with larger software apps, such as the Ruby on Rails app for web development. Ruby was designed to be simple and intuitive, making it a good option for beginning programmers.", video: "https://www.youtube.com/watch?v=IlVfHG-pAag", blog: "https://medium.com/@louis.shi/r-spec-represent-array-iteration-and-manipulation-beginner-edition-2409a120595c", course: "https://flatironschool.com/", book: "https://www.amazon.com/Rails-Way-Addison-Wesley-Professional-Ruby/dp/0134657675/ref=zg_bs_6134006011_1?_encoding=UTF8&psc=1&refRID=KN4A1NYFP3ZFV39DAKN2", school: "https://flatironschool.com/")
